/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-12-02 05:25:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.DB.DBConnect;
import java.sql.Connection;
import com.entity.User;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.entity.User");
    _jspx_imports_classes.add("com.DB.DBConnect");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Home.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\">\r\n");
      out.write("<link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"d-flex align-item-center justify-content-start\"\r\n");
      out.write("		style=\"background-color: #412236;\">\r\n");
      out.write("		<div class=\"logo ms-5 p-3\">\r\n");
      out.write("			<img src=\"images/logo-1.webp\" width=133px height=\"77px\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"nav-items d-flex\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"home.jsp\">home</a></li>\r\n");
      out.write("				<li><a href=\"about.jsp\">about</a></li>\r\n");
      out.write("				<li><a href=\"Programs.jsp\">pages</a></li>\r\n");
      out.write("				<li><a href=\"\">blog</a></li>\r\n");
      out.write("				<li><a href=\"contact.jsp\">contact</a></li>\r\n");
      out.write("				<li><a href=\"product.jsp\">Shop</a></li>\r\n");
      out.write("				<li class=\"\"><a href=\"login.jsp\"><i class=\"bi bi-person-circle\"></i></a>\r\n");
      out.write("					 ");

 User user = (User) session.getAttribute("userobj");
 if (user != null) {
 
      out.write("\r\n");
      out.write("					<span class=\"text-center ps-1 text-white fw-bold\">\r\n");
      out.write("\r\n");
      out.write("						");
      out.print(user.getName());
      out.write("</span> ");

 } else {
 // Handle the case where the user object is not found in the session.
 }
 
      out.write("</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"image-nav d-flex justify-content-center align-item-center\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<img data-aos=\"zoom-in\" data-aos-duration=\"3000\"\r\n");
      out.write("				src=\"images/buddha-statue-culture-faith-heritage-meditation-PXC4V5Q.jpg\"\r\n");
      out.write("				width=100% height=\"600px\" alt=\"\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"\"\r\n");
      out.write("		style=\"background-color: #FFF0E3; height: auto; padding-bottom: 50px;\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"container d-flex justify-content-between align-item-center\"\r\n");
      out.write("			style=\"padding-top: 200px;\">\r\n");
      out.write("			<div class=\"l-para\">\r\n");
      out.write("				<p id=\"wel\">WELCOME</p>\r\n");
      out.write("				<h3>Practice Mindfulness At Our Ashram</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"r-para\">\r\n");
      out.write("				<h6>We welcome newcomers to join us at any of our daily yoga\r\n");
      out.write("					classes and morning meditation on weekdays, or join one of our\r\n");
      out.write("					vibrant evening discussion groups.</h6>\r\n");
      out.write("				<h6>Stay at the Ashram and immerse yourself in our spiritual\r\n");
      out.write("					yogic lifestyle program with other like minded seekers.</h6>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"container-1 mt-5 d-flex justify-content-between align-item-center\">\r\n");
      out.write("			<div class=\"card text-center\" style=\"width: 18rem;\">\r\n");
      out.write("				<div class=\"text-center\">\r\n");
      out.write("					<img src=\"images/ashram.webp\" width=116px height=\"116px\"\r\n");
      out.write("						class=\"m-5\" alt=\"...\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h5 class=\"card-title\">Meditation</h5>\r\n");
      out.write("					<p class=\"card-text\">Tall, lofty mountains, lush green valleys\r\n");
      out.write("						and a starlit sky are the silent keepers of this ashram</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card text-center\" style=\"width: 18rem;\">\r\n");
      out.write("				<div class=\"text-center\">\r\n");
      out.write("					<img src=\"images/involve.webp\" width=116px height=\"116px\"\r\n");
      out.write("						class=\"m-5\" alt=\"...\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h5 class=\"card-title\">Yoga</h5>\r\n");
      out.write("					<p class=\"card-text\">The ashram is involved in a number of\r\n");
      out.write("						social causes for the local villagers, most of whom remain below</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card text-center\" style=\"width: 18rem;\">\r\n");
      out.write("				<div class=\"text-center\">\r\n");
      out.write("					<img src=\"images/donation.webp\" width=116px height=\"116px\"\r\n");
      out.write("						class=\"m-5\" alt=\"...\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h5 class=\"card-title\">Culture</h5>\r\n");
      out.write("					<p class=\"card-text\">You can get involved by donating to any of\r\n");
      out.write("						our programs. We would like to thank you for your contribution.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"program\">\r\n");
      out.write("			<p>PROGRAMS</p>\r\n");
      out.write("			<h1>Free Programs For Every Level Of Experience</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mt-5 d-flex justify-content-center align-item-center ig\">\r\n");
      out.write("			<img class=\"\"\r\n");
      out.write("				src=\"images/offerings-tibetan-water-bowls-in-lamayuru-gompa-CJSVBYP.jpg\"\r\n");
      out.write("				alt=\"\">\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("				<h3 style=\"\" id=\"b\">The Beginner's Program</h3>\r\n");
      out.write("				<p style=\"margin-left: 50px; max-width: 466px; margin-top: 20px;\">Powerful\r\n");
      out.write("					breathing techniques and wisdom that will transform your life.\r\n");
      out.write("					Equip yourself with practical knowledge and techniques to unlock\r\n");
      out.write("					your true potential and bring fullness to your life.</p>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mt-5 d-flex justify-content-center align-item-center\">\r\n");
      out.write("			<img src=\"images/one.jpg\" width=570px height=\"380px\" alt=\"\">\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("				<h3 style=\"margin-top: 110px; margin-left: 50px; max-width: 500px;\"\r\n");
      out.write("					id=\"b\">Becoming a Guru Program</h3>\r\n");
      out.write("				<p style=\"margin-left: 50px; max-width: 466px; margin-top: 20px;\">Go\r\n");
      out.write("					beyond your usually active mind and experience an extraordinary\r\n");
      out.write("					sense of peace and renewed vitality through guided meditations and\r\n");
      out.write("					other processes.</p>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"back\" style=\"text-align: center;\">\r\n");
      out.write("		<p>JOIN</p>\r\n");
      out.write("		<h2>Learn To Be Consciously Happy!</h2>\r\n");
      out.write("		<h6>Vihara Ashram is an ideal place for every person who is\r\n");
      out.write("			looking for personal development and rest from anxieties of modern\r\n");
      out.write("			life.</h6>\r\n");
      out.write("		<button>\r\n");
      out.write("			<a href=\"#\">more about us</a>\r\n");
      out.write("		</button>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("			<li><a href=\"about.jsp\">About</a></li>\r\n");
      out.write("			<li><a href=\"Programs.jsp\">Program</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<img src=\"images/logo-1.webp\" width=132px height=\"76px\" alt=\"\">\r\n");
      out.write("		<footer>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"\">Features</a></li>\r\n");
      out.write("				<li><a href=\"\">Blog</a></li>\r\n");
      out.write("				<li><a href=\"conntact.jsp\">Contactt</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\r\n");
      out.write("		<script>\r\n");
      out.write("			AOS.init();\r\n");
      out.write("		</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
