/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-12-02 05:26:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Product</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Product.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("        integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Home.css\">\r\n");
      out.write("    <link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Nova+Square&family=Roboto+Serif:ital,opsz,wght@0,8..144,100;0,8..144,200;0,8..144,300;0,8..144,400;0,8..144,500;1,8..144,100;1,8..144,200;1,8..144,300;1,8..144,400;1,8..144,500&display=swap');\r\n");
      out.write("\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"d-flex align-item-center justify-content-start\" style=\"background-color: #412236;\">\r\n");
      out.write("        <div class=\"logo ms-5 p-3\">\r\n");
      out.write("            <img src=\"images/logo-1.webp\" width=133px height=\"77px\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-items\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"home.jsp\">home</a></li>\r\n");
      out.write("                <li><a href=\"about.jsp\">about</a></li>\r\n");
      out.write("                <li><a href=\"Programs.jsp\">pages</a></li>\r\n");
      out.write("                <li><a href=\"\">blog</a></li>\r\n");
      out.write("                <li><a href=\"contact.jsp\">contact</a></li>\r\n");
      out.write("                <li><a href=\"product.\">Shop</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <h2 class=\"text-center\">All Products</h2>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-3\">\r\n");
      out.write("                <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("                    <img src=\"images/i1.webp\"  width=218px height=\"218px\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    <div class=\"card-body text-center\">\r\n");
      out.write("                        <h4 class=\"card-title fs-5 text-secondary\">Vilewadi Leham</h4>\r\n");
      out.write("                        <p class=\"card-text fs-6 text-secondary\">For Stomach Ache and Food Poisoning.</p>\r\n");
      out.write("                        <p class=\" text-secondary fw-bold\"><span\r\n");
      out.write("                                style=\"font-weight: bold;font-size: 20px;color: black;\">â¹</span> 50</p>\r\n");
      out.write("                        <div class=\"d-grid gap-2\">\r\n");
      out.write("                            <button class=\"btn  btn-outline-warning\" type=\"button\">Buy Now</button>\r\n");
      out.write("                            <button class=\"btn btn-warning\" type=\"button\">Add to cart</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-3\">\r\n");
      out.write("                <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("                    <img src=\"images/i1.webp\" width=218px height=\"218px\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    <div class=\"card-body text-center\">\r\n");
      out.write("                        <h4 class=\"card-title fs-5 text-secondary\">Vilewadi Leham</h4>\r\n");
      out.write("                        <p class=\"card-text fs-6 text-secondary\">For Stomach Ache and Food Poisoning.</p>\r\n");
      out.write("                        <p class=\" text-secondary fw-bold\"><span\r\n");
      out.write("                                style=\"font-weight: bold;font-size: 20px;color: black;\"><i class=\"bi bi-currency-rupee\"></i></span> 50</p>\r\n");
      out.write("                        <div class=\"d-grid gap-2\">\r\n");
      out.write("                            <button class=\"btn  btn-outline-warning\" type=\"button\">Buy Now</button>\r\n");
      out.write("                            <button class=\"btn btn-warning\" type=\"button\">Add to cart</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-3\">\r\n");
      out.write("                <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("                    <img src=\"images/i1.webp\"  width=218px height=\"218px\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    <div class=\"card-body text-center\">\r\n");
      out.write("                        <h4 class=\"card-title fs-5 text-secondary\">Vilewadi Leham</h4>\r\n");
      out.write("                        <p class=\"card-text fs-6 text-secondary\">For Stomach Ache and Food Poisoning.</p>\r\n");
      out.write("                        <p class=\" text-secondary fw-bold\"><span\r\n");
      out.write("                                style=\"font-weight: bold;font-size: 20px;color: black;\">â¹</span> 50</p>\r\n");
      out.write("                        <div class=\"d-grid gap-2\">\r\n");
      out.write("                            <button class=\"btn  btn-outline-warning\" type=\"button\">Buy Now</button>\r\n");
      out.write("                            <button class=\"btn btn-warning\" type=\"button\">Add to cart</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-3\">\r\n");
      out.write("                <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("                    <img src=\"images/i1.webp\"  width=218px height=\"218px\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    <div class=\"card-body text-center\">\r\n");
      out.write("                        <h4 class=\"card-title fs-5 text-secondary\">Vilewadi Leham</h4>\r\n");
      out.write("                        <p class=\"card-text fs-6 text-secondary\">For Stomach Ache and Food Poisoning.</p>\r\n");
      out.write("                        <p class=\" text-secondary fw-bold\"><span\r\n");
      out.write("                                style=\"font-weight: bold;font-size: 20px;color: black;\"><i class=\"bi bi-currency-rupee\"></i></span> 50</p>\r\n");
      out.write("                        <div class=\"d-grid gap-2\">\r\n");
      out.write("                            <button class=\"btn  btn-outline-warning\" type=\"button\">Buy Now</button>\r\n");
      out.write("                            <button class=\"btn btn-warning\" type=\"button\">Add to cart</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
